name: KeyHunt Automation

on:
  workflow_dispatch:  # Manually Run
  schedule:
    - cron: "50 */6 * * *"  # Runs every 5 hours 50 minutes

jobs:
  run-keyhunt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          git clone https://github.com/Ramavatar98/keyhunt-.git
          cd keyhunt-
          make

      - name: Run KeyHunt for 5 Hours 50 Minutes
        run: |
          cd keyhunt-
          timeout 20990 ./keyhunt -m address -f tests/66.txt -b 71 -t 8 -R -l compress -q -s 3600 | tee ../keyhunt_output.log

      - name: Display Key Found
        run: |
          cd keyhunt-
          cat KEYFOUNDKEYFOUND.txt
          
